### ISSUE TITLE
发送消息后不能收起键盘

### ISSUE THREAD

**Issue by HanFei0813** [FirstDKS521/DKSChatKeyboard#1]
- (void)textViewContentText:(NSString *)textStr

方法中尝试 
[self.view endEditing:YES];
OR
[[NSNotificationCenter defaultCenter] postNotificationName:@"keyboardHide" object:nil];
均不能收起键盘

**Comment by FirstDKS521** [comment]
这个之前写过一个demo，https://github.com/FirstDKS521/DKSProject，你可以参考一下------------------ 原始邮件 ------------------
发件人: "HanFeizi"<notifications@github.com>
发送时间: 2019年8月19日(星期一) 中午11:09
收件人: "FirstDKS521/DKSChatKeyboard"<DKSChatKeyboard@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [FirstDKS521/DKSChatKeyboard] 发送消息后不能收起键盘 (#1)


 
(void)textViewContentText:(NSString *)textStr
  
方法中尝试
 [self.view endEditing:YES];
 OR
 [[NSNotificationCenter defaultCenter] postNotificationName:@"keyboardHide" object:nil];
 均不能收起键盘
 
&mdash;
